<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Number_debitNumber</name>
   <tag></tag>
   <elementGuidId>22fd3b5a-3540-4e20-b6de-ace8914182b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#debitNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='debitNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e2136e0-7e9f-4173-97c1-f0c11e7e83ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>debitNumber</value>
      <webElementGuid>3a3da451-d658-4448-a222-2200a2fd85d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>debitNumber</value>
      <webElementGuid>bd4c4699-a856-4059-9102-3131eccd4843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>691fa847-112e-478a-a912-6e905e91ed99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>bc125a8d-d7d8-426d-8fe5-46fb53465ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paymentinput</value>
      <webElementGuid>ef57f1e9-c4b3-47a8-a513-85a656a5be70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>afa93eac-5aea-4197-8f59-37ea32c46692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:validateprefixid(this.value)</value>
      <webElementGuid>cabe7f81-e626-49b3-968b-8c816dfd4919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript:validateprefixid(this.value);</value>
      <webElementGuid>88ce3aac-9972-4081-9ca6-9bd6b9f58e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return ValidateNumPin(event);</value>
      <webElementGuid>cc0b5514-c6ca-488e-bb03-590ce06f79fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumPin(event);</value>
      <webElementGuid>266086f7-fa73-47a0-b1ae-99b94031b6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>d206f3b1-81fb-499a-a056-dc0a639c1dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>15a14a3d-0718-4eb9-8f88-bd14139f0da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>ca92d07c-14dc-4194-9f37-4c1901909a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Should be in number. Length should be 10</value>
      <webElementGuid>79cda494-318b-472d-a529-2f10a22ccd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;debitNumber&quot;)</value>
      <webElementGuid>92571ad5-f0eb-4b17-9e48-3bb646c2398f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='debitNumber']</value>
      <webElementGuid>11208c28-a56c-4f10-b6fd-b3f80b8c045d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Paymentpagecardnumber']/div[2]/label[2]/input</value>
      <webElementGuid>52a563ca-1a95-4e9f-beb3-4ee93c0413cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>e71bda47-be6e-4c81-a431-08564a02807c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'debitNumber' and @id = 'debitNumber' and @type = 'text' and @title = 'Should be in number. Length should be 10']</value>
      <webElementGuid>5a2d203a-b2d2-4d1e-a29d-4e3fb32ae9ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
