<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Processing. please wait_proceed</name>
   <tag></tag>
   <elementGuidId>2e02d566-0e8f-462d-bfee-772668b9b1dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proceed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proceed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fee61a9-4e43-4956-997f-a946736e70a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>proceed</value>
      <webElementGuid>e757723e-5521-46c9-ba8c-2ec727e22ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a52a7c2-abd6-4aec-a8dc-3cd5cedba77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3abd5edc-f6ba-4b29-852a-8a9660ed36e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onPay();</value>
      <webElementGuid>44219adb-6eb6-440e-bd68-19499c806e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proceed</value>
      <webElementGuid>3139179f-50e3-4a20-b2dc-3e26c2e4c48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>091dc523-d878-4edb-a41f-7eb901b3ed5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proceed&quot;)</value>
      <webElementGuid>cfc36169-86d3-41ab-a1f6-df6659ca4e66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proceed']</value>
      <webElementGuid>02936d31-f4ff-4229-9fbb-d7c4c871eced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PayPageEntry']/div/div[2]/div[4]/div/input</value>
      <webElementGuid>c24442e0-364a-401e-8daf-1bd91a291efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>b371efc1-ccd3-4cb2-9f1d-280d6ee442d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'proceed' and @type = 'button' and @id = 'proceed']</value>
      <webElementGuid>6fdb83c8-9380-430b-b184-3742c14f1ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
