<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Processing. please wait_confirm</name>
   <tag></tag>
   <elementGuidId>a07a4d2e-75e6-468f-b03b-fd2a1e8039c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proceedConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proceedConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2074da8-3add-4dab-b899-1547d0543c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90b3775a-8014-46e9-b1fb-a535536a0499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm</value>
      <webElementGuid>41b0a78a-7c7b-48c5-a2da-794b138025be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proceedConfirm</value>
      <webElementGuid>78473345-d84f-47f8-920c-5259298ada65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>fcd02662-90f6-4e2b-a246-248d509b3d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0233c86f-e6f1-4efa-85eb-4c323a951416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>payConfirmAjax('VALIDATE');</value>
      <webElementGuid>88d285e4-c448-4f5c-93b9-a3733055c7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proceedConfirm&quot;)</value>
      <webElementGuid>c57c62b1-d6d5-47f5-97a9-c46925183429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proceedConfirm']</value>
      <webElementGuid>55b0d0ce-6c72-4704-b4c4-c57e300db1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payConfirm']/div/div[2]/div[9]/div/input</value>
      <webElementGuid>e7ab3686-1155-460c-9a6f-c602cf6fcae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>4e5341c5-526d-4153-85f3-99349477473f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'confirm' and @id = 'proceedConfirm']</value>
      <webElementGuid>80480175-5eb3-46fb-bf9b-8283df9c49f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
