<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PIN_cardPin</name>
   <tag></tag>
   <elementGuidId>62082e28-f29c-4ee2-9fc6-18b1aa1029b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardPin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardPin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87c3bcb9-c48b-427f-8c4e-93195beb7414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardPin</value>
      <webElementGuid>192778ec-5626-451f-866e-f4f97139b10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardPin</value>
      <webElementGuid>77d94790-d6e3-4392-b1c5-f8876e94ce26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c6d9cd5d-6ac9-41a4-815c-aba848f27917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Should be in number. Length should be 4</value>
      <webElementGuid>29c27313-dd4e-4ad5-a1f5-d385bcef4b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9356485c-6422-4273-bab7-02243ef1886e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6c9f832e-1a2a-4515-9448-c511cd60dcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>86996c00-3023-493f-ae79-50adda564fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paymentinput pin</value>
      <webElementGuid>86a1b4b5-6fe3-4e70-b704-1fb585657595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return ValidateNumPin(event);</value>
      <webElementGuid>eb32d2be-d305-4404-919f-508ca6f65c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumPin(event);</value>
      <webElementGuid>f1674b56-a466-4ee0-992f-e1fc3d42ea2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>814e02c8-68b7-4f75-9336-a2764d8316a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>77c196b8-84f3-4613-900e-307110bb15a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>23f8f89f-887b-4709-af86-e5e5ae716b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardPin&quot;)</value>
      <webElementGuid>a1f4f77c-fc47-4447-ad63-166ea41d8ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardPin']</value>
      <webElementGuid>129ca478-f21a-43e4-93ce-529dc6866fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PinField']/div[2]/input</value>
      <webElementGuid>00f2715f-1720-45e5-a045-8e73aed16d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>cc090cdf-641a-4a99-9f0f-72579342b9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cardPin' and @id = 'cardPin' and @title = 'Should be in number. Length should be 4' and @type = 'password']</value>
      <webElementGuid>c2da0576-23f6-4a60-9b6d-080151252d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
