<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Member</name>
   <tag></tag>
   <elementGuidId>fe7d278f-21cd-458f-beef-5ac9a067547e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/ul[2]/li[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52131dc2-5dd7-4c05-a693-11e3d8f11a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://stg-booking.jazeeraairways.com/en/?showMemberLogin&amp;culture=en-kw&amp;_ga=2.77847444.1899916910.1693830132-1719346142.1693830132</value>
      <webElementGuid>f7d90867-7c41-42d8-83f4-4dc6488093d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>3b976d36-6c2c-4fd4-8f9f-87b517bc61b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Member</value>
      <webElementGuid>0fe53b9f-6a3f-4bb2-b32d-f2b9765555e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-inner desktop_navigation&quot;]/ul[@class=&quot;toggle-btns&quot;]/li[@class=&quot;header-login-menu&quot;]/div[@class=&quot;btn-dropdown-menu rounded show&quot;]/div[@class=&quot;profile-menu&quot;]/div[@class=&quot;dropdown-option loginbtn&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>b090fbc0-3649-44b1-adab-44e0bb7537c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/ul[2]/li[2]/div/div/div/a</value>
      <webElementGuid>e890143f-c164-4d16-a48f-93394eee6b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Member')]</value>
      <webElementGuid>dea37c18-869d-4565-b913-d702d86bef17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عربي'])[29]/following::a[2]</value>
      <webElementGuid>6efc0313-a3b3-4d7f-b3aa-3739edec53d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[29]/following::a[3]</value>
      <webElementGuid>6cd5124e-c41a-405d-81e0-f61115d2089d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::a[1]</value>
      <webElementGuid>74187faf-c3e3-440d-affb-af34277536ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kw'])[2]/preceding::a[3]</value>
      <webElementGuid>44af4d33-79f9-4365-8615-c2c4b9537e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Member']/parent::*</value>
      <webElementGuid>97e1f6bc-6cbe-40d1-b8e3-5b88024a3427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://stg-booking.jazeeraairways.com/en/?showMemberLogin&amp;culture=en-kw&amp;_ga=2.77847444.1899916910.1693830132-1719346142.1693830132')]</value>
      <webElementGuid>06c2b831-1f26-4620-97f4-6024701a6c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/a</value>
      <webElementGuid>80d105a7-7bd3-4b17-83cd-8efbdd637ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://stg-booking.jazeeraairways.com/en/?showMemberLogin&amp;culture=en-kw&amp;_ga=2.77847444.1899916910.1693830132-1719346142.1693830132' and (text() = 'Member' or . = 'Member')]</value>
      <webElementGuid>71b69f9e-a230-4d51-9d1d-417cb8c3b127</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
