<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_One Way</name>
   <tag></tag>
   <elementGuidId>e8a6ddf9-7dde-4292-b2a4-ae3600001e33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flights']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>270d4347-c96f-4045-a464-49c558211b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#one-way</value>
      <webElementGuid>c6775a47-22c9-42c6-9554-613a1108a5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link btn-switch</value>
      <webElementGuid>70b70bbe-b7eb-43cb-8e91-463f67b8fbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>One Way</value>
      <webElementGuid>a2856b86-5a54-4be0-b023-d55d4785e12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flights&quot;)/div[@class=&quot;switch-sub-panel&quot;]/a[@class=&quot;btn btn-link btn-switch&quot;]</value>
      <webElementGuid>040804e5-4863-4346-bf11-dc8ceaf46a92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flights']/div/a[2]</value>
      <webElementGuid>9436a876-0195-46a9-a4d1-a79bf526e696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'One Way')]</value>
      <webElementGuid>a02ef5af-fc0d-4573-b1f0-bc14ac3356ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[1]/following::a[1]</value>
      <webElementGuid>3826e5f6-bd48-413b-992d-c08fa9ef5c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[4]/following::a[2]</value>
      <webElementGuid>8e99a416-ae5c-46fc-ba60-b470ce741030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi City'])[1]/preceding::a[1]</value>
      <webElementGuid>464a91c1-59ce-47f3-849d-955c8ed0bc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SelectDepatureAirport'])[1]/preceding::a[3]</value>
      <webElementGuid>a15fb096-cb77-41f0-95bb-99332aa0b34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='One Way']/parent::*</value>
      <webElementGuid>ba764e47-f27a-4e3a-8e58-eccb7892d396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#one-way')]</value>
      <webElementGuid>701d92f7-c1cd-447c-82e6-67da51a9ec8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div[2]/div/a[2]</value>
      <webElementGuid>58c899de-87ca-45a1-afe4-ad93e1644db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#one-way' and (text() = 'One Way' or . = 'One Way')]</value>
      <webElementGuid>873e1e21-bdff-4262-8b82-26abf53f8d0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
