<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Partners</name>
   <tag></tag>
   <elementGuidId>5338f3f7-3555-4152-9c73-9e8c081f52c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/ul[2]/li[2]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db46c8a4-50b3-47b4-942e-fb52b8dc28c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-kw/partners</value>
      <webElementGuid>a736af2d-627d-48a8-9db5-02f4e2065cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>5582c1fa-3115-4686-86b7-2b1a1f8f4a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Partners</value>
      <webElementGuid>afaa8e04-1674-4aa5-b7da-bc436895a477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-inner desktop_navigation&quot;]/ul[@class=&quot;toggle-btns&quot;]/li[@class=&quot;header-login-menu&quot;]/div[@class=&quot;btn-dropdown-menu rounded show&quot;]/div[@class=&quot;profile-menu&quot;]/div[@class=&quot;dropdown-option loginbtn&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>3c24af11-19e2-405e-b252-500c74e9ffda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/ul[2]/li[2]/div/div/div[2]/a</value>
      <webElementGuid>2122a551-f29e-409c-beab-f2e0e397ec1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Partners')]</value>
      <webElementGuid>dd5f79cb-8942-4f55-848d-6328654443d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::a[1]</value>
      <webElementGuid>9b745901-1c81-413c-a455-01c9cdd0697a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عربي'])[29]/following::a[3]</value>
      <webElementGuid>ebaa0691-afb1-4339-b9d5-2231f7ea9847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kw'])[2]/preceding::a[2]</value>
      <webElementGuid>43d88e47-60c2-4d7a-9200-1cd39cbf87f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='en'])[3]/preceding::a[2]</value>
      <webElementGuid>d0ba1848-0123-4f9d-8c38-81e9fdd29bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Partners']/parent::*</value>
      <webElementGuid>0e32f639-ca72-4172-a4b3-aa29108244a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-kw/partners')]</value>
      <webElementGuid>0c2c727d-a285-4324-8831-b369f37d65ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/a</value>
      <webElementGuid>482e00e0-01d9-4577-90a2-8e1b98168603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-kw/partners' and (text() = ' Partners' or . = ' Partners')]</value>
      <webElementGuid>cfdebf47-0774-41f5-ae47-2785959bdf44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
