<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dont Allow</name>
   <tag></tag>
   <elementGuidId>a3bb1222-880e-4aca-af24-0b835430863e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moe-dontallow_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='moe-dontallow_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb8fa2f9-3162-4263-af31-d80c97fec42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moe-dontallow_button</value>
      <webElementGuid>1c22642f-6e2e-4baa-80e1-4f521570efba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': webPushPreview['bannerv2']['web']['closeButton']['color'],'background':webPushPreview['bannerv2']['web']['closeButton']['backgroundColor']}</value>
      <webElementGuid>13778d19-1f16-480b-9a70-c087147848b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>deaf321d-da9b-4ca7-99b9-bcd8bfd7fdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Don't Allow</value>
      <webElementGuid>5ac66161-a4bb-4ae5-9874-56bfc06c2be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moe-dontallow_button&quot;)</value>
      <webElementGuid>ba8a69cd-c1e9-47b8-86ae-f528a3e471d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='moe-dontallow_button']</value>
      <webElementGuid>8c6fc8bf-388e-4f1c-ac4f-82055c5accd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopBannerWrapped']/div/div[3]/div/button</value>
      <webElementGuid>fd5cfe7a-f110-4b98-99d2-541e8f2b441e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jazeera Airways would like to send you awesome updates and offers!'])[1]/following::button[1]</value>
      <webElementGuid>6ac38220-f827-4f13-9aca-6606f462f5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow'])[1]/preceding::button[1]</value>
      <webElementGuid>c585eedc-8af6-4eca-859f-e7f46540b3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Information'])[1]/preceding::button[2]</value>
      <webElementGuid>18b91b10-5054-4c8e-8fee-bf434e95dec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0af6e24a-9a68-4791-827c-8e2651c9a681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'moe-dontallow_button' and (text() = concat(&quot;Don&quot; , &quot;'&quot; , &quot;t Allow&quot;) or . = concat(&quot;Don&quot; , &quot;'&quot; , &quot;t Allow&quot;))]</value>
      <webElementGuid>bf9378bc-6ca1-418f-b685-a76fc2cbbfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use the below coupon code to get a discount on your next flight ticket!'])[1]/preceding::button[2]</value>
      <webElementGuid>4ce32611-2605-45d8-b694-690331369e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
