<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>7daeef62-2bd8-4b66-b25a-3b81fe052da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-row.row.group-field > div.col-md-2 > div.btn-wrap.align-right > button.btn.btn-primary.btn-lg.btn-icon-right.login-message-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='loadAnalyticsDataForFlightsOneWayType();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f51738e-787d-4b10-a75d-e0078e09c05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg btn-icon-right login-message-search</value>
      <webElementGuid>bb48585c-f54e-4b78-9c91-c3be47ba4822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>loadAnalyticsDataForFlightsOneWayType();</value>
      <webElementGuid>78551757-8b4b-4cda-a64b-eaf93f191457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search  </value>
      <webElementGuid>8436a1d9-6594-441d-913e-8adf0254ab6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchOneWayFlight&quot;)/div[@class=&quot;form-wrap&quot;]/div[@class=&quot;form-row row group-field&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;btn-wrap align-right&quot;]/button[@class=&quot;btn btn-primary btn-lg btn-icon-right login-message-search&quot;]</value>
      <webElementGuid>3a9ed579-046c-4e52-9339-b30b98f09b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='loadAnalyticsDataForFlightsOneWayType();']</value>
      <webElementGuid>8bd15c4d-d5ae-4d3f-9d63-f93a9d8fbcb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div[2]/div[3]/div/button</value>
      <webElementGuid>a9c6e99a-2e29-441a-a6aa-752c7042e254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[8]/following::button[1]</value>
      <webElementGuid>af4ff111-28e7-426f-98a6-ba8e93602333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[8]/following::button[2]</value>
      <webElementGuid>cdc3fbd3-6334-4ae4-bed7-2aa7b9f6ff8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Promo Code'])[2]/preceding::button[1]</value>
      <webElementGuid>baaa5cfc-eea0-4b00-9bf8-b4f500253ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Fares'])[2]/preceding::button[1]</value>
      <webElementGuid>cb729625-c4ff-4d9f-8ad0-a7c1324316f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div[2]/div[3]/div/button</value>
      <webElementGuid>83c7518f-5257-4450-9f4b-c9e0313e5978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Search  ' or . = 'Search  ')]</value>
      <webElementGuid>79b77af4-73ce-4218-84f0-a7dfbb766528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
