<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Learn more_bx-modal__btn-close-icon</name>
   <tag></tag>
   <elementGuidId>d7aaa7aa-2d42-4695-9bc0-fa36b6f814e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bx-modal__btn-close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bx-modal_overlay']/div/custom/custom/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d72df37c-303b-4e5d-9efc-122e66f9ad28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx-modal__btn-close-icon</value>
      <webElementGuid>b82daadb-9a74-4125-ba16-d1d01d878c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bx-modal_overlay&quot;)/div[@class=&quot;bx-modal_content lang-en&quot;]/custom[1]/custom[1]/div[@class=&quot;bx-modal__btn-close-icon&quot;]</value>
      <webElementGuid>256320ed-b667-45fe-8efd-104bce293cdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bx-modal_overlay']/div/custom/custom/div</value>
      <webElementGuid>312657d6-b1b6-4a49-8974-b2965d6182fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//custom/div</value>
      <webElementGuid>b277312d-64b8-4c8a-8042-93ae40a807f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
