<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>7a310722-34db-4e0b-8480-2bfce8391857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='departure_flight_search_oneway_range_picker']/div/div/table[2]/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.day.toMonth.valid.tmp.hovering</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c849b511-2fe6-4225-96ec-099fa563622f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>time</name>
      <type>Main</type>
      <value>1696107600000</value>
      <webElementGuid>b915c248-c223-4159-9731-1763bf5ddd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>day toMonth  valid  tmp hovering</value>
      <webElementGuid>5706c4cc-0465-4f80-afed-b229aebf07e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>322870a2-3909-4a80-9b61-7e58e717a414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departure_flight_search_oneway_range_picker&quot;)/div[@class=&quot;date-picker-wrapper single-date  no-shortcuts  no-topbar  inline-wrapper no-gap two-months&quot;]/div[@class=&quot;month-wrapper&quot;]/table[@class=&quot;month2&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;day toMonth  valid  tmp hovering&quot;]</value>
      <webElementGuid>5389c3ec-2bfd-4a39-90b0-b67b75810788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='departure_flight_search_oneway_range_picker']/div/div/table[2]/tbody/tr/td/div</value>
      <webElementGuid>b3a66f9e-de31-45f0-b2c5-8bccd5152683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sat'])[2]/following::div[1]</value>
      <webElementGuid>9cbbdd65-3dbe-43e4-97d8-2133d14cafc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fri'])[2]/following::div[1]</value>
      <webElementGuid>3b15e851-5b30-422c-a3e0-54110aac3db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passengers'])[2]/preceding::div[41]</value>
      <webElementGuid>1739786f-d031-406e-b57a-3e49d0ff2340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/div</value>
      <webElementGuid>fb521747-7cce-48e4-8bc0-5ecd34717575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1' or . = '1')]</value>
      <webElementGuid>ce8e2c63-c1ef-412a-ad86-cc96addcb913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
