<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_october_icon icon-arrow-up</name>
   <tag></tag>
   <elementGuidId>fc43a0e0-c8db-4b74-8cb9-7526c64e5b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-dropdown.login-btn-dropdown.show > i.icon.icon-arrow-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/ul[2]/li[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>98ceb7d4-3ce5-4fee-9d36-178efa3ea2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-arrow-down</value>
      <webElementGuid>84de3743-d645-4f43-9407-b7704da72248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-inner desktop_navigation&quot;]/ul[@class=&quot;toggle-btns&quot;]/li[@class=&quot;header-login-menu&quot;]/a[@class=&quot;btn btn-dropdown login-btn-dropdown show&quot;]/i[@class=&quot;icon icon-arrow-down&quot;]</value>
      <webElementGuid>8ee6a64b-1605-4feb-9537-ab49dd0d5c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/ul[2]/li[2]/a/i</value>
      <webElementGuid>cec4a3a3-fe04-4ed1-b006-adb7491809e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/i</value>
      <webElementGuid>5f310212-ee8e-4ff2-bca5-56dcd55bf733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='departure_flight_search_oneway_range_picker']/div/div/table[2]/thead/tr/th[3]/span/i</value>
      <webElementGuid>c6eff496-2e4b-457c-be63-1eac40ac8e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/thead/tr/th[3]/span/i</value>
      <webElementGuid>11d12991-4e62-4dce-8515-4b09aa999b86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
