<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To_to_flight_search_oneway</name>
   <tag></tag>
   <elementGuidId>d67437d0-e93f-4ae6-9b7f-0f96458b6da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#to_flight_search_oneway</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='to_flight_search_oneway']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc843d8c-7ce7-4e4f-bef2-6601fa08062e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>to_flight_search_oneway</value>
      <webElementGuid>a5738f67-c2aa-4cbf-93fb-9f5451b17714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>to_flight_search_oneway</value>
      <webElementGuid>6cc7a5fa-5080-4171-8818-18b3b5171d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77c4553b-b6d9-4ecc-b470-75136357abb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-invert location-select to tt-input</value>
      <webElementGuid>6ad233a1-4942-4250-ab34-46a1ce444192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b98f0ad5-2992-4407-a10c-82ba75cfc7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>To</value>
      <webElementGuid>1d4e2f93-a0c8-43e9-b712-c5571ebd5a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a20b9e9f-7ff9-4609-a291-1020d7b3d247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d958be4-8658-4fc3-bea1-9b1253da7798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>fa04cead-427f-4ffa-b754-fec539493aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to_flight_search_oneway&quot;)</value>
      <webElementGuid>ed09a642-bebd-40b8-9178-bac52012c55f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to_flight_search_oneway']</value>
      <webElementGuid>44c9c6f8-fa04-4158-91a2-8244015461fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div/div[2]/div[2]/span[4]/input[2]</value>
      <webElementGuid>84a4ceb6-678d-4d69-97da-48b6c022098d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/input[2]</value>
      <webElementGuid>78651d30-5c71-4d95-b498-d82e8160528c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'to_flight_search_oneway' and @name = 'to_flight_search_oneway' and @type = 'text' and @placeholder = 'To']</value>
      <webElementGuid>3b0d5fd6-ec1c-4db0-bacb-bc5883f740a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
