<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_from_flight_search_oneway</name>
   <tag></tag>
   <elementGuidId>0f4985ad-d674-41e9-bf8d-c9da294513f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from_flight_search_oneway</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from_flight_search_oneway']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b18f681-5473-4b51-9271-eda35d9af93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from_flight_search_oneway</value>
      <webElementGuid>0ed8ff82-82c2-4c8a-abb6-f3fae53bae76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>from_flight_search_oneway</value>
      <webElementGuid>bfc50101-e09e-43df-8b7e-fa94e9985d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40de0e71-a617-48ab-8681-6280acbd3233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-invert location-select from tt-input</value>
      <webElementGuid>721c3b72-20a7-47d1-81cc-922dbce6a8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>685721df-f4b0-4528-935c-b4156555ed4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From</value>
      <webElementGuid>72c2b5e3-09d3-4920-b9b6-835b85a2568a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7fca70a0-d2b5-4210-8f71-00ede43a329c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d2af35d-e64d-47e5-b9b5-66cdf46adbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>7503f04e-1978-4a36-aaac-10a132ba543e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from_flight_search_oneway&quot;)</value>
      <webElementGuid>e46e02ef-67ee-4f5c-a232-de335fe1b0cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from_flight_search_oneway']</value>
      <webElementGuid>df8fd327-3071-4ac1-950f-0447d09c8d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div/div/div[2]/span[3]/input[2]</value>
      <webElementGuid>753413e6-e46d-4064-8b60-c21431a2a018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div/div/div[2]/span[3]/input[2]</value>
      <webElementGuid>ea6b0607-33c3-4b4d-b364-5a3d2aad5af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'from_flight_search_oneway' and @name = 'from_flight_search_oneway' and @type = 'text' and @placeholder = 'From']</value>
      <webElementGuid>2112d8e4-0686-432f-a79d-468e28fa60f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
