<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_september (1)</name>
   <tag></tag>
   <elementGuidId>af15f586-4a36-45fa-b4ee-3166e284442b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='return_flight_date_range']/div/div/table/thead/tr/th[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#return_flight_date_range > div.date-picker-wrapper.no-shortcuts.no-topbar.inline-wrapper.no-gap.two-months > div.month-wrapper > table.month1 > thead > tr.caption > th.month-name > div.month-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c214db6-572d-4dbe-a960-5f5987c1c14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month-element</value>
      <webElementGuid>9af7447d-dc7d-4181-bcb1-5e3953309c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>september</value>
      <webElementGuid>33d6afa7-f07e-4f68-8271-866653d93d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return_flight_date_range&quot;)/div[@class=&quot;date-picker-wrapper no-shortcuts  no-topbar  inline-wrapper no-gap two-months&quot;]/div[@class=&quot;month-wrapper&quot;]/table[@class=&quot;month1&quot;]/thead[1]/tr[@class=&quot;caption&quot;]/th[@class=&quot;month-name&quot;]/div[@class=&quot;month-element&quot;]</value>
      <webElementGuid>c7588747-4eb0-49e4-bdf8-679f19d77bdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return_flight_date_range']/div/div/table/thead/tr/th[2]/div</value>
      <webElementGuid>30fba55f-e3e1-4377-9878-1ac69c83d588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose your return date'])[1]/following::div[5]</value>
      <webElementGuid>26613a2c-c148-4e48-906e-5ecb3341694f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ReturnDate'])[1]/following::div[6]</value>
      <webElementGuid>ac5b807f-d953-465e-ba86-b017285cd58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sun'])[3]/preceding::div[2]</value>
      <webElementGuid>9304c1f9-8cf2-434b-b749-5aff39921e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mon'])[3]/preceding::div[2]</value>
      <webElementGuid>95f3fc6c-5cee-4b1f-9339-cb6c90127a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div/div/table/thead/tr/th[2]/div</value>
      <webElementGuid>4c531b45-9502-4945-af3c-21de38e90d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'september' or . = 'september')]</value>
      <webElementGuid>2547d15d-1340-4558-a3bc-0cf94aa0d0a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
