<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_october (1)</name>
   <tag></tag>
   <elementGuidId>273260ef-fe19-4cb7-b4ad-30b35159f1e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='return_flight_date_range']/div/div/table[2]/thead/tr/th[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#return_flight_date_range > div.date-picker-wrapper.no-shortcuts.no-topbar.inline-wrapper.no-gap.two-months > div.month-wrapper > table.month2 > thead > tr.caption > th.month-name > div.month-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5302282-be83-419d-a31e-3ae85df3dd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month-element</value>
      <webElementGuid>ee3fa11e-0d09-41db-93c8-9f023896bd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>october</value>
      <webElementGuid>9f96aa36-e383-4753-97bd-952dc3e24777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return_flight_date_range&quot;)/div[@class=&quot;date-picker-wrapper no-shortcuts  no-topbar  inline-wrapper no-gap two-months&quot;]/div[@class=&quot;month-wrapper&quot;]/table[@class=&quot;month2&quot;]/thead[1]/tr[@class=&quot;caption&quot;]/th[@class=&quot;month-name&quot;]/div[@class=&quot;month-element&quot;]</value>
      <webElementGuid>ab13325c-1993-4456-8d76-183940bd0d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return_flight_date_range']/div/div/table[2]/thead/tr/th[2]/div</value>
      <webElementGuid>f6e65e30-14d3-4bff-b5ff-f005a15cc5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sat'])[3]/following::div[120]</value>
      <webElementGuid>d73b24f0-e9bb-4c2d-a4a4-c95947ebc25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fri'])[3]/following::div[120]</value>
      <webElementGuid>b5564e14-a468-4230-9eab-7fc4912c7700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sun'])[4]/preceding::div[2]</value>
      <webElementGuid>49cbbdbd-86f9-412a-873e-f2b9225e346c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mon'])[4]/preceding::div[2]</value>
      <webElementGuid>9bd30acc-b794-4163-8fdd-d8ee0ea9c2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div/div/table[2]/thead/tr/th[2]/div</value>
      <webElementGuid>5c2be0fe-21e8-4e9a-abca-27dbd7862bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'october' or . = 'october')]</value>
      <webElementGuid>971c0c36-21be-48b8-936a-6bed084726d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
