<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Departure_departure_flight_search</name>
   <tag></tag>
   <elementGuidId>a880afe0-6d94-4e5f-a34e-01b0b7515fbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='departure_flight_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#departure_flight_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2671ea5-0133-4bbf-94f0-9ae6cf59fe99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>departure_flight_search</value>
      <webElementGuid>6b37ca71-bb7f-4d7f-9586-e875161f7f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>departure_flight_search</value>
      <webElementGuid>b934b433-62ed-4fe5-b55f-9015e5f38903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e70db4a9-f139-4c40-b819-600c90d2c6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-invert datepicker travel-backdrop</value>
      <webElementGuid>043c9a03-e3df-42b8-a91c-6446b5d40335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8881078d-a517-416c-8652-8a1407950328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Departure</value>
      <webElementGuid>4e9777f1-a157-43fc-98b0-21823d838ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6cd0fa61-4e34-4afe-ad4f-bb113331d160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departure_flight_search&quot;)</value>
      <webElementGuid>8745e1ff-3233-48d3-8cc4-a6be7ae1d164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='departure_flight_search']</value>
      <webElementGuid>164cf790-d00d-4fad-98e1-f0ea367147d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReturnFlight']/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>ca370fe7-a6ff-4927-b5d8-c731bf2db60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>18b69b64-a49b-4a55-b58d-0ccfcb969d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'departure_flight_search' and @name = 'departure_flight_search' and @type = 'text' and @placeholder = 'Departure']</value>
      <webElementGuid>d3b50a0a-d3b4-4991-a23b-4aefe5abbb94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
