<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Oneway_Flight_Date</name>
   <tag></tag>
   <elementGuidId>19ed7e5b-a2b8-4539-92f6-81695ab20b5d</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Flight Tickets  Flight Offers - Book Online  Jazeera Airways Kuwait/Input_Oneway_Flight_Date.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='departure_flight_search_oneway']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Flight Tickets  Flight Offers - Book Online  Jazeera Airways Kuwait/Input_Oneway_Flight_Date.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#departure_flight_search_oneway</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91dd3289-6736-4003-aa32-e5b34822195f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>departure_flight_search_oneway</value>
      <webElementGuid>84f23842-2c70-4706-a2d7-61af550127ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>departure_flight_search_oneway</value>
      <webElementGuid>560bacf7-2f88-4ece-8855-f68eea809ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29ea69ad-b6f1-494a-87d8-5c806d3e0074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-invert calendar-date-picker2 single-date-picker datepicker travel-backdrop</value>
      <webElementGuid>a8d9c148-57c9-4b4b-b7fc-20031431a43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e6253b06-2f6f-4e14-b652-408b5197ee97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Departure</value>
      <webElementGuid>7196e485-9bb5-43a7-9081-b335a7c48062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>71d55c11-6225-451d-ba76-6a14b0a860a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departure_flight_search_oneway&quot;)</value>
      <webElementGuid>19575eb7-3921-40d2-bfeb-a753b2b4c48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>departure_flight_search_oneway-error</value>
      <webElementGuid>af2668e7-52e8-4ce5-ba84-66ec2a960f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f6d5bcb-e8ab-485d-bc9c-c8a21deef1b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='departure_flight_search_oneway']</value>
      <webElementGuid>8422d1b0-aaf0-49a2-9273-ce8ba18d6d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div[2]/div/div/div/input</value>
      <webElementGuid>41fb20a8-ae19-4598-9e32-71c424327257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>144aed85-275b-4371-8ae9-e912e9e7ae83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'departure_flight_search_oneway' and @name = 'departure_flight_search_oneway' and @type = 'text' and @placeholder = 'Departure']</value>
      <webElementGuid>eef61f53-e6a7-4d2f-b8df-05dd0efa7601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
