<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Return_return_flight_search</name>
   <tag></tag>
   <elementGuidId>97c3e594-e774-48e3-9bc1-fc43680f2f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='return_flight_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#return_flight_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c469874-b10e-4db1-bab7-3df82dcb4a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>return_flight_search</value>
      <webElementGuid>1f3489fa-2061-4d19-8670-fbb2fe4de239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>return_flight_search</value>
      <webElementGuid>13a6778c-62f3-471e-85da-a9edd40ab721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>818c3504-4f7f-4904-aab1-02465640fb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-invert datepicker travel-backdrop1</value>
      <webElementGuid>3baf33dd-c88c-4ec9-98c2-1ed248e011bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>23aaeee4-5820-4a5d-b173-fecf98522210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Return</value>
      <webElementGuid>cf049283-751d-4f5f-b329-91dac9c0977c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>08b9bb15-8289-4cc3-9005-4d6b2b06e97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>return_flight_search-error</value>
      <webElementGuid>c69d6fcd-c749-4123-b22a-effe9e3fbb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e799342a-8025-408f-9a37-78dfd3fdae01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return_flight_search&quot;)</value>
      <webElementGuid>7638b1c5-e9d8-425e-b723-7962fa1c47e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='return_flight_search']</value>
      <webElementGuid>ecd9af53-d8f1-43d5-8242-1cdd81510123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReturnFlight']/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>4d07fd4e-0508-452a-b8c5-409e0df2db6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>1134607a-081b-4a68-bf34-acd09c18c4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'return_flight_search' and @name = 'return_flight_search' and @type = 'text' and @placeholder = 'Return']</value>
      <webElementGuid>e68f33df-202f-43d7-a743-4ddab639a401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
