<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RT_DepartureDate_input</name>
   <tag></tag>
   <elementGuidId>f973006e-3ecd-4da4-b356-212499712a18</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Flight Tickets  Flight Offers - Book Online  Jazeera Airways Kuwait/RT_DepartureDate_input.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='departure_flight_search']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Flight Tickets  Flight Offers - Book Online  Jazeera Airways Kuwait/RT_DepartureDate_input.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#departure_flight_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aefb7f3-7c63-4779-b00c-7fcb172866d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>departure_flight_search</value>
      <webElementGuid>270e75e9-87b3-4621-927f-0ec5be03cef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>departure_flight_search</value>
      <webElementGuid>eb50d58e-8d1b-4715-8f40-33f47ff7f42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4854813-ff3b-4404-bea0-2440b7373926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-invert datepicker travel-backdrop</value>
      <webElementGuid>d92baab3-6687-407e-883f-7b8866253d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a93c9b20-09ae-4bed-bf67-aedd88a3d8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Departure</value>
      <webElementGuid>c8e7bc00-a59e-4a61-8221-452746841fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>620f206f-ae5f-4d26-9cd1-91571137eb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departure_flight_search&quot;)</value>
      <webElementGuid>493aa545-2b5c-4bfa-9e4e-ad043c263e88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='departure_flight_search']</value>
      <webElementGuid>8a9a323c-746a-4ecd-a771-9c8e4f57c323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReturnFlight']/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>4e0cbd17-e9b2-469b-b364-444bb0c53e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>9b43acc5-f28a-4f36-ab85-e539a9b2ed01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'departure_flight_search' and @name = 'departure_flight_search' and @type = 'text' and @placeholder = 'Departure']</value>
      <webElementGuid>f611ce33-f8b7-4d90-81aa-9297cb9b7ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
