<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RT_ReturnDate_Month2</name>
   <tag></tag>
   <elementGuidId>985bcd03-61c6-4d42-b91c-c0052da4ec40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='return_flight_date_range']/div/div/table[2]/thead/tr/th[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#return_flight_date_range > div.date-picker-wrapper.no-shortcuts.no-topbar.inline-wrapper.no-gap.two-months > div.month-wrapper > table.month2 > thead > tr.caption > th.month-name > div.month-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5028f86b-dcfc-4909-99fb-c58414bd8267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month-element</value>
      <webElementGuid>32f4ed3c-9d1f-4ef6-bd33-280f476565bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>october</value>
      <webElementGuid>0421074c-8781-4beb-97a3-fbe0c2ae71d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return_flight_date_range&quot;)/div[@class=&quot;date-picker-wrapper no-shortcuts  no-topbar  inline-wrapper no-gap two-months&quot;]/div[@class=&quot;month-wrapper&quot;]/table[@class=&quot;month2&quot;]/thead[1]/tr[@class=&quot;caption&quot;]/th[@class=&quot;month-name&quot;]/div[@class=&quot;month-element&quot;]</value>
      <webElementGuid>db647f65-9d9b-447a-b411-95c2d83ace02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return_flight_date_range']/div/div/table[2]/thead/tr/th[2]/div</value>
      <webElementGuid>9a414c38-22d8-49ec-a2e2-40541bda77c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sat'])[3]/following::div[120]</value>
      <webElementGuid>4bbd76b6-c301-40bd-809b-806852ad6f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fri'])[3]/following::div[120]</value>
      <webElementGuid>ff799d49-c5a1-49e9-ba4f-cfac784abed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sun'])[4]/preceding::div[2]</value>
      <webElementGuid>d5d1410d-219f-4e3e-99e4-6c20c5284ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mon'])[4]/preceding::div[2]</value>
      <webElementGuid>cadc9ca4-f043-4ddf-bb12-0deb6c0db4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div/div/table[2]/thead/tr/th[2]/div</value>
      <webElementGuid>52c7bacc-aee8-473e-ba4b-8051e1551e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'october' or . = 'october')]</value>
      <webElementGuid>945e0d13-afd8-4bb5-86b6-b5287b31b097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
