<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RT_ReturnDate_Year2</name>
   <tag></tag>
   <elementGuidId>4ee179af-1e10-4acd-a7e3-0f7ebf2045ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='return_flight_date_range']/div/div/table[2]/thead/tr/th[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8db81f0c-ca91-4cc1-b555-118e966e9837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month-element</value>
      <webElementGuid>6b21d64b-cb55-467d-a88c-f29023d51530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2023</value>
      <webElementGuid>dad81f7c-823b-4637-91ac-c698bee00937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return_flight_date_range&quot;)/div[@class=&quot;date-picker-wrapper no-shortcuts  no-topbar  inline-wrapper no-gap two-months&quot;]/div[@class=&quot;month-wrapper&quot;]/table[@class=&quot;month2&quot;]/thead[1]/tr[@class=&quot;caption&quot;]/th[@class=&quot;month-name&quot;]/div[@class=&quot;month-element&quot;]</value>
      <webElementGuid>5ec0deec-6fe6-46fe-b504-6914d11c989f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return_flight_date_range']/div/div/table[2]/thead/tr/th[2]/div[2]</value>
      <webElementGuid>b9518623-1b8d-469c-abca-88aca428a597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='october'])[2]/following::div[1]</value>
      <webElementGuid>6b6e8689-37af-4c39-ae06-ff9290270fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sat'])[3]/following::div[121]</value>
      <webElementGuid>f91300b4-0f9e-4670-bbb6-06bc8808b8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sun'])[4]/preceding::div[1]</value>
      <webElementGuid>3d2fe185-7834-4677-83d3-d4875ea5d682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mon'])[4]/preceding::div[1]</value>
      <webElementGuid>d2f5e62c-7001-4606-99dc-ad20b7965fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div/div/table[2]/thead/tr/th[2]/div[2]</value>
      <webElementGuid>c5026331-3aef-402f-a444-aac4ec4c3195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2023' or . = '2023')]</value>
      <webElementGuid>8cd8ab81-1f57-4e35-9309-7b65f0667762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
