<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RT_ReturnDate_Input</name>
   <tag></tag>
   <elementGuidId>49c5dd68-fbfa-4419-a087-6c956f6ba54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='return_flight_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#return_flight_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7a535ae-5362-4a59-a51d-ebcee1e1fffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>return_flight_search</value>
      <webElementGuid>51ebef4a-ed28-4a96-964d-9c6525136a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>return_flight_search</value>
      <webElementGuid>7405cac1-da2a-48a7-931f-18d58e5660d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12f6b109-895a-449d-90ea-6fb0fb1acb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-invert datepicker travel-backdrop1</value>
      <webElementGuid>2d36ee39-cbc8-4f67-9d53-f5e124ff960f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d84b19ac-7e39-421e-bdbc-74c7fb9fefd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Return</value>
      <webElementGuid>f443179c-8595-446e-925b-204d5ef2fa6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e91ff3f7-3afb-492e-8c98-95ca16769a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return_flight_search&quot;)</value>
      <webElementGuid>c0fafe61-d345-4723-b44d-28fad4b3dc23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='return_flight_search']</value>
      <webElementGuid>fa1b67c9-abf4-425e-8b97-a96d0c876337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReturnFlight']/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>51d44b49-7a56-4e5d-b551-58186ea16797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>160ac70e-d04b-4e79-9227-b5b9cb5cd910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'return_flight_search' and @name = 'return_flight_search' and @type = 'text' and @placeholder = 'Return']</value>
      <webElementGuid>f8cdc657-fcc1-49b7-80d1-608010a1cf66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
