<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>d572bfdb-4f8d-453b-b67d-d1eb256dd8f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-dropdown.login-btn-dropdown.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/ul[2]/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd153f71-b890-42a7-86eb-70b205f5e7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://stg-booking.jazeeraairways.com/en/search-flight?showAgencyLogin=&amp;culture=en-kw&amp;_ga=2.142830581.1169101345.1693899777-634010071.1693899777</value>
      <webElementGuid>b7acd98d-9745-4651-912f-4a49daac7368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dropdown login-btn-dropdown show</value>
      <webElementGuid>cd5bf1ca-f954-4793-bf3c-ca4c1060d214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login</value>
      <webElementGuid>8773396e-b319-41fc-a9a0-9b19ae91ef0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-inner desktop_navigation&quot;]/ul[@class=&quot;toggle-btns&quot;]/li[@class=&quot;header-login-menu&quot;]/a[@class=&quot;btn btn-dropdown login-btn-dropdown show&quot;]</value>
      <webElementGuid>3684305e-ff62-4ff6-97f5-bc7e7129ecd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/ul[2]/li[2]/a</value>
      <webElementGuid>053ea2c8-7b13-4ddb-8187-bb2ff392f935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>0308dcdf-051a-4961-b61f-df7144f1cf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عربي'])[29]/following::a[1]</value>
      <webElementGuid>f46a8ac8-ab56-4e92-9e89-8e13b8fae979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[29]/following::a[2]</value>
      <webElementGuid>dcddf7db-fc72-4e11-8d77-decfabce010c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kw'])[2]/preceding::a[2]</value>
      <webElementGuid>bd1ad480-bc56-4f02-94a7-e0405b974d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='en'])[3]/preceding::a[2]</value>
      <webElementGuid>c91b560f-356f-4f77-8bea-cb887642f765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>07df1852-f36b-4973-8a62-5de55014b9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://stg-booking.jazeeraairways.com/en/search-flight?showAgencyLogin=&amp;culture=en-kw&amp;_ga=2.142830581.1169101345.1693899777-634010071.1693899777')]</value>
      <webElementGuid>0c077d4e-516d-4e45-a29c-cd53565340a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/a</value>
      <webElementGuid>90ca16c5-b38a-452d-a0c9-174692460b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://stg-booking.jazeeraairways.com/en/search-flight?showAgencyLogin=&amp;culture=en-kw&amp;_ga=2.142830581.1169101345.1693899777-634010071.1693899777' and (text() = ' Login' or . = ' Login')]</value>
      <webElementGuid>b995e536-a7ab-4ecc-98e4-b8f3fff944f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
