<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Seat</name>
   <tag></tag>
   <elementGuidId>c6a0384b-17b2-4295-bc45-08ac28cb1c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='seatSelectionWrap']/div/div/div/div/div/app-seats-selection-leg/div/div/div/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0a0bc23-9680-4c9d-b8fa-7603afb21241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>f6d1c0fa-4085-4cec-a8f5-e7b55c6272fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Seat </value>
      <webElementGuid>06473195-b5d9-4c9b-8beb-e8c8a0b3737f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seatSelectionWrap&quot;)/div[@class=&quot;mapseat1 ng-star-inserted&quot;]/div[@class=&quot;mapseat2&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;addons_journey_div&quot;]/div[1]/app-seats-selection-leg[@class=&quot;card accordion-item ng-star-inserted&quot;]/div[@class=&quot;seats_selection_leg_div ng-star-inserted&quot;]/div[@class=&quot;journey_passengers_details_div ng-star-inserted&quot;]/div[@class=&quot;row seat_selection_row&quot;]/div[@class=&quot;col-md-4 modify_select_button_div&quot;]/button[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>5f2f12ac-4bcf-408f-a693-9bf309423247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='seatSelectionWrap']/div/div/div/div/div/app-seats-selection-leg/div/div/div/div[3]/button</value>
      <webElementGuid>f7812db2-4d11-4817-8595-ff0f1b616989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MR Test Check'])[1]/following::button[1]</value>
      <webElementGuid>465ac02b-5cfa-4ad7-a583-f541f4384e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KWI - DXB'])[1]/following::button[1]</value>
      <webElementGuid>d5c74075-8e73-493b-a7c2-e2bd4394ac9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/preceding::button[1]</value>
      <webElementGuid>286a14d3-8890-494b-bd9e-42a2b3fff082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLOSE'])[1]/preceding::button[1]</value>
      <webElementGuid>5cb242aa-50e0-407d-8abd-450952609650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Seat']/parent::*</value>
      <webElementGuid>632c6ff3-98cb-4fe8-9a1a-2ad77accb7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>c2ad26b7-8850-4313-b744-d1a164e40742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Select Seat ' or . = 'Select Seat ')]</value>
      <webElementGuid>d50980a2-2d67-4ae6-a49f-97a8762b0eb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
