<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>7eb0458c-330c-4722-9b09-009a5724b17d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-2.search-btn-container.ng-star-inserted.shown > div.btn-wrap.align-right > button.btn.btn-primary.btn-lg.btn-searchFlights.btn-icon-right.px-3.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>877cd3dd-4063-4e03-a56f-57542cf278e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>26b76a50-648a-4582-a11b-9d60b8c8f62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg btn-searchFlights btn-icon-right px-3 w-100</value>
      <webElementGuid>8a213b35-fc31-4347-a3f5-7778b32d5d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search </value>
      <webElementGuid>9e060677-ae64-4072-831e-c85caf849d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchOneWayFlight&quot;)/div[@class=&quot;form-wrap&quot;]/div[@class=&quot;form-row row group-field shown&quot;]/div[@class=&quot;col-md-2 search-btn-container ng-star-inserted shown&quot;]/div[@class=&quot;btn-wrap align-right&quot;]/button[@class=&quot;btn btn-primary btn-lg btn-searchFlights btn-icon-right px-3 w-100&quot;]</value>
      <webElementGuid>768f513b-9d06-4577-95d7-273837acbae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>8fd2146d-28a4-4da9-8766-9574b870f513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div[2]/div[3]/div/button</value>
      <webElementGuid>0957b50c-8b84-4cb5-b6f2-8e33733df9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[8]/following::button[1]</value>
      <webElementGuid>6933173c-abe9-4555-8ec1-abcaa1d48336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[8]/following::button[2]</value>
      <webElementGuid>ae9cb2dd-4c01-4c6a-b2b5-d10340910430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Promo Code'])[2]/preceding::button[1]</value>
      <webElementGuid>d43bea0b-a002-404c-9ead-f1a3a7638c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Fares'])[2]/preceding::button[1]</value>
      <webElementGuid>02dc4a91-88aa-48b5-affd-dbc87aa32bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modify-search-one-way/div/form/div/div[2]/div[3]/div/button</value>
      <webElementGuid>c675a5d0-dacf-4907-890c-edf05073fbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Search ' or . = ' Search ')]</value>
      <webElementGuid>0ca6349d-96a3-4613-8dad-67ba4dc22f73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
