<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>0c4960e1-ef52-4dd7-8d04-0d606f5445ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.panel-footer-Extra.text-center > button.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Sjl_IDEyMX4gfn5LV0l_MTAvMDEvMjAyMyAwNzoyMH5EWEJ_MTAvMDEvMjAyMyAxMDowNX5_Lightuifare']/app-flight-select-drop-down/div/section/div/div/div[4]/div/div[2]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2702539-cb1c-4104-9cd6-faefefec6d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>4458ced4-19ad-4a38-ad34-d7d4d7634077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>e0fc1736-9090-4a28-b99b-bc59448a44c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Sjl_IDEyMX4gfn5LV0l_MTAvMDEvMjAyMyAwNzoyMH5EWEJ_MTAvMDEvMjAyMyAxMDowNX5_Lightuifare&quot;)/app-flight-select-drop-down[1]/div[@class=&quot;economy-border striped-four-block&quot;]/section[@class=&quot;plans&quot;]/div[@class=&quot;container d-none d-sm-block&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3 ng-star-inserted&quot;]/div[@class=&quot;panel panel-danger panel-pricing active&quot;]/div[2]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;panel-footer-Extra text-center&quot;]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>e2693334-baf5-4f79-8256-6e0ab33ccc41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Sjl_IDEyMX4gfn5LV0l_MTAvMDEvMjAyMyAwNzoyMH5EWEJ_MTAvMDEvMjAyMyAxMDowNX5_Lightuifare']/app-flight-select-drop-down/div/section/div/div/div[4]/div/div[2]/div/div[2]/button</value>
      <webElementGuid>adcc6ef4-99a4-46bb-af9a-929f0d249933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KWD 31.000'])[1]/following::button[1]</value>
      <webElementGuid>ac091632-7a33-4f69-8d17-c201f355511a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay to Cancel up to 24 Hours prior to departure'])[2]/following::button[1]</value>
      <webElementGuid>1728125d-381c-4e9a-9cea-2b1f61b74e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fare Rules'])[3]/preceding::button[1]</value>
      <webElementGuid>98d8546a-9661-4ea2-808c-345092619a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Light'])[2]/preceding::button[2]</value>
      <webElementGuid>57f821c4-2ec3-4266-8333-2d8bd546a889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[2]/button</value>
      <webElementGuid>50fc9d69-a50c-4250-8fd1-7641cf486039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>afdcf011-9f18-41ed-a18a-b632be9e62ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Sjl_IDEyMX4gfn5LV0l_MTEvMTUvMjAyMyAwNzoxNX5EWEJ_MTEvMTUvMjAyMyAxMDowNX5_Lightuifare']/app-flight-select-drop-down/div/section/div/div/div[4]/div/div[2]/div/div[2]/button</value>
      <webElementGuid>1b3cfb70-7940-4527-a89e-54a3e109c279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Sjl_IDEyMX4gfn5LV0l_MTEvMTUvMjAyMyAwNzoxNX5EWEJ_MTEvMTUvMjAyMyAxMDowNX5_Extrauifare']/app-flight-select-drop-down/div/section/div/div/div[4]/div/div[2]/div/div[2]/button</value>
      <webElementGuid>e88a3924-6ca3-4294-9b2f-dd97935341c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KWD 37.000'])[14]/following::button[1]</value>
      <webElementGuid>c351d9b3-7b12-47fb-8050-e80664031796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only 4seats left!'])[1]/following::button[1]</value>
      <webElementGuid>a6f83368-12dd-4e74-b743-13a1eea2e634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fare Rules'])[1]/preceding::button[1]</value>
      <webElementGuid>cfafb548-19bf-4701-8b56-3190cf2d5112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>fcbb0fa5-58ff-4c89-bb1d-cdb3407e3e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>fa85b138-4f02-4b47-86c8-e7e2bd457c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
