<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kuwait</name>
   <tag></tag>
   <elementGuidId>aefdee50-856b-47da-97da-0e47c565d900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a74f4681de04-43</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a74f4681de04-43']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27703b24-ea44-445f-aec3-ffbfeb011e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>5fd3d91c-0050-4f5e-8f11-2b372c0e6438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>884b6711-2150-4953-a550-ed0d689f3392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32cd70e8-8ded-468e-a4a4-b8c58d83cca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a74f4681de04-43</value>
      <webElementGuid>66e44aed-f510-453a-979a-98b9f70af547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kuwait</value>
      <webElementGuid>42bb379e-6232-48e3-a5fb-3bbdb70d0604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a74f4681de04-43&quot;)</value>
      <webElementGuid>3771bcca-a0c5-4333-b20a-66f72ed25f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a74f4681de04-43']</value>
      <webElementGuid>cbdb4edf-ee32-4530-8534-b4176586af88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a74f4681de04']/div/div[2]/div</value>
      <webElementGuid>17b552a0-e68d-4ec8-8f41-93a2e0ee22fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[2]/following::div[11]</value>
      <webElementGuid>f75c4a77-f050-40cd-b24a-14d687bb43a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name'])[2]/following::div[13]</value>
      <webElementGuid>40c8332f-f121-422c-8685-1c046bb3d372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country of residence'])[1]/preceding::div[1]</value>
      <webElementGuid>e672a0da-47a0-468f-a487-12144ec55b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>41628bb5-30e8-4757-950d-9f4efb75989d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a74f4681de04-43' and (text() = 'Kuwait' or . = 'Kuwait')]</value>
      <webElementGuid>550992d9-5a24-45c8-a109-266ba0455aae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
