<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dubai</name>
   <tag></tag>
   <elementGuidId>492ad0dd-8aa3-4ffa-9227-f83492f54951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='searchOneWayFlight']/div/div/div[2]/div[2]/span[2]/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tt-menu.is-open > div.tt-dataset.tt-dataset-airports-list > div.tt-suggestion.Typeahead-suggestion.Typeahead-selectable > div.suggetion-title > div.country-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4b508358-62b2-4071-8992-61d0c48ddd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-title</value>
      <webElementGuid>bc3bcdd8-37af-45b8-b684-2b1f64c576f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dubai</value>
      <webElementGuid>145a13cf-87d4-4c01-a522-c0cb5a10e619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchOneWayFlight&quot;)/div[@class=&quot;form-wrap&quot;]/div[@class=&quot;form-row row location-ltr&quot;]/div[@class=&quot;col-md-6 locations show-popup&quot;]/div[@class=&quot;form-field float-label-wrapper focused populated&quot;]/span[@class=&quot;twitter-typeahead&quot;]/div[@class=&quot;tt-menu is-open&quot;]/div[@class=&quot;tt-dataset tt-dataset-airports-list&quot;]/div[@class=&quot;tt-suggestion Typeahead-suggestion Typeahead-selectable&quot;]/div[@class=&quot;suggetion-title&quot;]/div[@class=&quot;country-title&quot;]</value>
      <webElementGuid>3dab5508-71f8-4640-a184-746c69af68ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div/div[2]/div[2]/span[2]/div/div/div/div[2]/div</value>
      <webElementGuid>39a7cad5-45b0-47fd-a00e-2ab2165d2a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All locations'])[2]/following::div[4]</value>
      <webElementGuid>97efd289-7aff-417a-a3d2-3ea40bb8d5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[2]/following::div[6]</value>
      <webElementGuid>80932a14-5d53-42e9-8add-a62babff120c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Arab Emirates'])[1]/preceding::div[1]</value>
      <webElementGuid>fb211e16-d4f1-4112-970c-a3d987ac35d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ai']/parent::*</value>
      <webElementGuid>3cd28218-a70d-4e1b-bf73-120935ae60df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span[2]/div/div/div/div[2]/div</value>
      <webElementGuid>a6d7b9ec-aaa1-4e03-acbd-3de9e0ed8166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dubai' or . = 'Dubai')]</value>
      <webElementGuid>5f5d4934-7ee8-4902-96ed-a432e1934988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
