<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_15</name>
   <tag></tag>
   <elementGuidId>db148e52-4148-4ca6-9303-2221f681c6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.day.toMonth.valid.hovering</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '15' or . = '15')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/bs-datepicker-container/div/div/div/div/bs-days-calendar-view/bs-calendar-layout/div[2]/table/tbody/tr[1]/td[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d70afc6-bc61-4803-b436-c2a625529377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>time</name>
      <type>Main</type>
      <value>1700051233234</value>
      <webElementGuid>909155ee-1e55-4838-bb41-3bf09d63a679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>day toMonth valid hovering</value>
      <webElementGuid>9d452072-e197-418c-86d0-d00f0c478c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f56b5c42-40fa-4c9c-8638-066154b8ab1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departure_flight_search_oneway_range_picker&quot;)/div[@class=&quot;date-picker-wrapper single-date no-shortcuts no-topbar inline-wrapper no-gap two-months&quot;]/div[@class=&quot;month-wrapper&quot;]/table[@class=&quot;month2&quot;]/tbody[1]/tr[3]/td[4]/div[@class=&quot;day toMonth valid hovering&quot;]</value>
      <webElementGuid>b5cccf4c-332e-40df-a7c5-6cf98e91c28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='departure_flight_search_oneway_range_picker']/div/div/table[2]/tbody/tr[3]/td[4]/div</value>
      <webElementGuid>fd5fc860-8216-4645-bd90-dc371493cdfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sat'])[6]/following::div[18]</value>
      <webElementGuid>41c469fb-10ee-45ad-800d-d0b1978a71ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fri'])[6]/following::div[18]</value>
      <webElementGuid>9307ca3a-387d-4b85-b725-87aef878f8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passengers'])[2]/preceding::div[24]</value>
      <webElementGuid>7e07c708-316b-4be5-b3fd-a5ac7d9fd49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modify-search-one-way/div/form/div/div[2]/div/div/div[2]/div[3]/div/div/table[2]/tbody/tr[3]/td[4]/div</value>
      <webElementGuid>b2d36557-6e83-4680-b75a-a7421a781c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '15' or . = '15')]</value>
      <webElementGuid>f92436de-17d1-48b6-8733-1e14c0ab7296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
