<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_titleLast0</name>
   <tag></tag>
   <elementGuidId>ac0a3a5d-6b2d-4f08-84e8-18f890f8c692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titleLast0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='titleLast0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4af7262d-b480-4d25-9a81-c04b53cc0989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode == 32) || (event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode > 96 &amp;&amp; event.charCode &lt; 123)</value>
      <webElementGuid>99467837-eb4e-4b71-bb22-6333fdfbf3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>094c4ae9-e24c-4b15-8ccc-eea06beec787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^A-Za-z\s]/g, ''),(/^[\u0621-\u064A\u0660-\u0669 ]+$/,'');</value>
      <webElementGuid>bc8f0078-9019-4905-bc27-5c14e3d666f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>7aee7456-c077-4800-a2b2-db8f3d90e69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>fdc50a76-e2c5-4523-a0ba-22e585ddaa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aa77590f-7900-4c75-9317-4e7517943515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NcontactDetails0 form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a93f9240-b634-47f2-9185-376b628ad43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titleLast0</value>
      <webElementGuid>4c97be35-4de1-4931-a6f7-69261e196743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name </value>
      <webElementGuid>908735ea-6e66-4ab0-aa09-f463e339c5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleLast0&quot;)</value>
      <webElementGuid>9f2a1d31-328d-490f-998a-e6c552283095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='titleLast0']</value>
      <webElementGuid>50d0f2c4-4b2a-4cbe-a9df-b73206651c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse0']/div/div/div[2]/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>42e4abea-4b62-4926-9b53-caee9da3858b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>9cd7677b-db22-4cd5-b537-7abdfe67bc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'titleLast0' and @placeholder = 'Last Name ']</value>
      <webElementGuid>8c2d98d8-2ed7-421b-974b-54b8e7d1ab25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
