<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nationality_AdultDob</name>
   <tag></tag>
   <elementGuidId>b7452946-afa6-4c74-b4c6-77875972a4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AdultDob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AdultDob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d214e735-f29a-48ab-bc14-587960544b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>151da13d-0a78-4552-bcdd-55d1b676772d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AdultDob</value>
      <webElementGuid>625ed659-f033-4fc0-93f6-182728188d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>passengerDOB</value>
      <webElementGuid>481e1edd-6262-4eb1-b087-9498ea2c13b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>61ddf1a7-7758-43d0-9200-a393627edb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker-dropdown ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>aa2ad15f-2fcb-4f58-b639-436760c1ab07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>f1210a1d-ea21-4285-9b12-1b1faf42255d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AdultDob&quot;)</value>
      <webElementGuid>a66290d4-bd7a-4ef8-b88c-5691e7619b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AdultDob']</value>
      <webElementGuid>645cced0-b406-4e65-8f3b-444488ec05bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse0']/div/div/div[2]/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>8ccae777-46fe-4379-99d4-649e068d557c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>789d8019-6855-41af-a78e-69af6bb96241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'AdultDob' and @placeholder = 'Date of Birth']</value>
      <webElementGuid>49b33ac0-507b-4c64-a491-8812d0dd1cf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
