<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Partners Login_agency-login-password</name>
   <tag></tag>
   <elementGuidId>b6e50715-97d2-44b1-9516-e10624feff53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agency-login-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agency-login-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac6b693d-9d3a-4bcd-a1d2-e361325e5eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^A-Za-z0-9@.\s]/g, ''),(/^[\u0621-\u064A\u0660-\u0669 ]+$/,'');</value>
      <webElementGuid>87818a53-5c97-48b9-8d75-392d20aef243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>e9a50b54-5840-418a-8178-357a069cf4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ((event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode > 96 &amp;&amp; event.charCode &lt; 123) || event.charCode == 8 || event.charCode == 32 || (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57));</value>
      <webElementGuid>1b5c9724-3e59-4d30-862c-83963ef924da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f53a988f-0895-4e06-a00f-325173301683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>agencyPassword</value>
      <webElementGuid>b5a89046-1d96-4a98-97ff-884344b43b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agency-login-password</value>
      <webElementGuid>29a9cd74-5072-4e04-bfc7-2b4890d681ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agency-login-password</value>
      <webElementGuid>ebffca98-bb22-47a7-97c4-0aee01f54e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ffb71a0e-0e91-4b5f-a070-cd3bdaf12197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc8c8fe5-74e8-4261-a52c-05e3f4bc6c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>47177847-ecf2-4fb7-b2b1-bf50b5966811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>8e1ff20a-d9fa-4517-9617-48220d0197de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agency-login-password&quot;)</value>
      <webElementGuid>3a2b92ae-d00d-4f41-9259-049ca7e1f7e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agency-login-password']</value>
      <webElementGuid>d2c59141-efb0-4e52-9b68-429e63ea808c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='agencyLoginForm']/div[3]/div/div/input</value>
      <webElementGuid>285b7a14-271b-4bd2-bdf2-65f308d0cfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[3]/div/div/input</value>
      <webElementGuid>c4e6c3da-19ed-4e47-bad7-38c20a1a23b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'agency-login-password' and @name = 'agency-login-password' and @type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>1160ac50-1c8b-44e0-afca-25e969970efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
