<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Partners Login_agency-login-user-id</name>
   <tag></tag>
   <elementGuidId>98de7a7e-715e-410b-8b5d-0228e1703629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agency-login-user-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agency-login-user-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80113ad8-7906-4a2b-85fc-eb75ce635e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(!/^[-!#$%&amp;'*+\/0-9=?A-Z^_a-z`{|}~](\.?[-!#$%&amp;'*+\/0-9=?A-Z^_a-z`{|}~])*@[a-zA-Z0-9](-*\.?[a-zA-Z0-9])*\.[a-zA-Z](-?[a-zA-Z0-9])+$/,'').replace(/^[\u0621-\u064A\u0660-\u0669 ]+$/,'');</value>
      <webElementGuid>60b85cf8-11bb-49f9-8fc9-e0d3240fec6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>agencyUserName</value>
      <webElementGuid>18c57b3f-a196-479f-8f24-1e715204a78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agency-login-user-id</value>
      <webElementGuid>09b384bc-256c-47c6-b3df-1a44656ce731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agency-login-user-id</value>
      <webElementGuid>5c9bfed1-e548-4659-a4b2-9dbdc13525a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09d51796-c6ff-4e67-bdff-c459732408c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Agency User ID</value>
      <webElementGuid>28042ae6-03c7-4543-b925-b0cab85c81f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>86eea17f-2b77-4c7a-9ea3-0807e0ab8623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agency-login-user-id&quot;)</value>
      <webElementGuid>b204716b-598a-491f-b79b-8220ab40599f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agency-login-user-id']</value>
      <webElementGuid>80fb1c37-cf3d-4fb7-a1e7-901621fee282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='agencyLoginForm']/div[2]/div/div/input</value>
      <webElementGuid>66be4495-b036-49c5-a37b-456f7f5af788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/div/div/input</value>
      <webElementGuid>86ede3a1-bb71-4c20-95cb-30927f1885a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'agency-login-user-id' and @name = 'agency-login-user-id' and @type = 'text' and @placeholder = 'Agency User ID']</value>
      <webElementGuid>b38298cc-939e-4308-87eb-948de8652a84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
