<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_from_one_way_flight_searchsearchFlight</name>
   <tag></tag>
   <elementGuidId>cf5b3df3-f1da-4ff8-8aae-5040b393da0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from_one_way_flight_searchsearchFlight']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#from_one_way_flight_searchsearchFlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>820e0f2d-c807-4de9-a726-5e46d0296cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>fromPlace</value>
      <webElementGuid>9cabea3b-a662-474a-9449-b18df89baf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18d0043f-0c5c-404a-8982-40489d730982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d9d9f1c3-93a8-4464-818b-6cc228a7739b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e9dac3cf-0baf-4d9f-92e3-104a15fb7f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control flight-search-input font-weight-bold input-invert location-select place-hldr-color ng-untouched ng-pristine ng-valid tt-input</value>
      <webElementGuid>1f2aca54-0d27-42ad-b0ff-4603b6235537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from_one_way_flight_searchsearchFlight</value>
      <webElementGuid>ee98e18b-c35d-4930-9092-27044f775c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From</value>
      <webElementGuid>47b7d5b0-f146-4154-9b87-fb49c7feaa29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ccf3513e-c7be-437c-90ec-020003f43281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4ac41ab7-bc18-454c-801b-94ff4d62a7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from_one_way_flight_searchsearchFlight&quot;)</value>
      <webElementGuid>8a4ec6f5-f9ad-426c-83d2-344871a6351f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from_one_way_flight_searchsearchFlight']</value>
      <webElementGuid>5ef27260-ed5e-4f0b-bfde-ede2ca851b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div/div/div[2]/span[2]/input[2]</value>
      <webElementGuid>6a64586b-010a-4b3a-8739-7324c94c0056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modify-search-one-way/div/form/div/div/div/div[2]/span[2]/input[2]</value>
      <webElementGuid>36af8870-af90-4af7-8041-6fc929540331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'from_one_way_flight_searchsearchFlight' and @placeholder = 'From']</value>
      <webElementGuid>62ff201c-8101-459c-871e-f7b243beb8a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
