<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Member Login_member-login-user-id</name>
   <tag></tag>
   <elementGuidId>16f51714-c8b1-46cf-9bcd-fedf988f3ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='member-login-user-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#member-login-user-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>228bb010-be9e-4a40-a4f6-10a5bdf5e3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^-%&amp;'+\/0-9?A-Z^_a-z@.]/g, '')</value>
      <webElementGuid>b40c8025-2aa7-474b-8d1b-827406b21b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fb304e98-b470-40cb-8489-997d8688d1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>member-login-user-id</value>
      <webElementGuid>00549446-3005-4e02-9f20-ed374502183d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member-login-user-id</value>
      <webElementGuid>19a4fbd7-66f9-4621-9550-2e40d490cfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c829e28-5672-48b8-a452-584a9250551b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c8915a61-5382-47b0-aac1-a1bf4b5f71c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Member User ID/Email Address</value>
      <webElementGuid>b310fbc7-54e7-40fd-9e44-adbdf6ac2cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;member-login-user-id&quot;)</value>
      <webElementGuid>d2d78843-d975-4c79-b4c3-7c0951c277d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='member-login-user-id']</value>
      <webElementGuid>10edca2f-a438-4793-bf7f-2a63bfdbb6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MemberLoginForm']/div[2]/div/div/input</value>
      <webElementGuid>1ff67c5d-0245-496a-8527-3d9830a76cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>054ab0be-f797-4302-9b89-6646fe653ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'member-login-user-id' and @name = 'member-login-user-id' and @type = 'text' and @placeholder = 'Member User ID/Email Address']</value>
      <webElementGuid>64f2f2a5-5b46-419f-82c1-cef554afdafa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
