<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_titleFirst0</name>
   <tag></tag>
   <elementGuidId>40c4a66b-57f1-4a31-a6ee-b61dded073ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titleFirst0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='titleFirst0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b1a1098-8907-42df-90f7-be7876cdc98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^A-Za-z\s]/g, '');</value>
      <webElementGuid>e3183f71-b9e7-4da1-bd16-947280167e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode == 32) || (event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode > 96 &amp;&amp; event.charCode &lt; 123)</value>
      <webElementGuid>307a9ac5-523f-4347-ba89-d9a9feb7b083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8ba4c9b-d5ec-4d7d-9e3b-4a10608a9e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>dfb580eb-128a-4bcc-a151-c73e7ed1ac32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>6068cafc-100d-444b-9fbd-afd0ce64f17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>46166bb2-7e07-48ef-80ff-c15f6f358b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control1 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6897e4e3-c285-43c6-ac6e-fa2b28469c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titleFirst0</value>
      <webElementGuid>b4ca4c23-913c-4c0e-b4e8-47fa1ac1e1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name </value>
      <webElementGuid>05d59339-30ac-4f34-a305-5cb08573fcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleFirst0&quot;)</value>
      <webElementGuid>b2321be3-aa49-4b24-9d72-f7973842a058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='titleFirst0']</value>
      <webElementGuid>c4137f89-9f31-4c59-b114-60ab0c763c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse0']/div/div/div[2]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>86e4ce6b-a37c-45a3-923d-865c77e41cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9db0c473-6deb-4992-a7cc-06876fa3ac94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'titleFirst0' and @placeholder = 'First name ']</value>
      <webElementGuid>ade6d781-72ba-42f0-ac90-54dbeb879d6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
